# Generated by Django 3.0.4 on 2020-04-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('rg', models.CharField(blank=True, max_length=10, null=True)),
                ('expedidor', models.CharField(blank=True, max_length=12, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('titulo', models.CharField(blank=True, max_length=12, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=15, null=True)),
                ('natural', models.CharField(blank=True, max_length=30, null=True)),
                ('qtd_dependentes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rua', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=4, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('celular1', models.CharField(blank=True, max_length=15, null=True)),
                ('celular2', models.CharField(blank=True, max_length=15, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
