# Generated by Django 3.0.4 on 2020-04-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('U', 'Uniao estável'), ('D', 'Divorciado(a)'), ('V', 'Viuvo(a)')], max_length=1, null=True),
        ),
    ]
