# Generated by Django 3.0.6 on 2020-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20200513_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
