# Generated by Django 3.0.6 on 2020-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('codproduto', models.AutoField(primary_key=True, serialize=False, verbose_name='codigo do produto')),
                ('descproduto', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('unidade', models.CharField(max_length=20)),
                ('fornecedor', models.CharField(max_length=100)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('situacao', models.CharField(choices=[('D', 'disponível'), ('I', 'indisponivel')], max_length=20, null=True)),
            ],
        ),
    ]
