# Generated by Django 3.0.6 on 2020-05-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descproduto',
            field=models.CharField(max_length=150, verbose_name='produto'),
        ),
    ]
