# Generated by Django 3.0.4 on 2020-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='bio',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
