# Generated by Django 3.0.6 on 2020-05-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postagem_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='autor',
            new_name='Produto',
        ),
        migrations.RenameField(
            model_name='postagem',
            old_name='data_publicacao',
            new_name='data_entrega',
        ),
        migrations.RenameField(
            model_name='postagem',
            old_name='data_criacao',
            new_name='data_pedido',
        ),
        migrations.RenameField(
            model_name='postagem',
            old_name='titulo',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='postagem',
            old_name='texto',
            new_name='observacao',
        ),
    ]
