# Generated by Django 3.0.6 on 2020-05-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200513_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='Produto',
            new_name='produto',
        ),
    ]
