# Generated by Django 3.0.6 on 2020-05-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20200513_1738'),
        ('blog', '0004_auto_20200513_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produtos'),
        ),
    ]
